#!/bin/sh

set -e
ln -s /home/sqale/etc/hikiconf.rb /home/sqale/current/hikiconf.rb
ln -s /home/sqale/etc/rubima /home/sqale/current/public/theme/rubima
ln -s /home/sqale/etc/htpasswd /home/sqale/current/.htpasswd
